global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:465'
  smtp_from: '${EMAIL_HOST_USER}'
  smtp_auth_username: '${EMAIL_HOST_USER}'
  smtp_auth_password: '${EMAIL_HOST_PASSWORD}'
  smtp_require_tls: false

route:
  receiver: 'email-notifications'
    
receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '${EMAIL_HOST_USER}'
        send_resolved: true