global:
  scrape_interval: 30s

rule_files:
  - "prometheus-alerts.yml"  # 👈 This tells Prometheus to load your alert rules
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'django-uptime-api'
    static_configs:
      - targets: ['web:8000']
