# Generated by Django 5.2.4 on 2025-07-21 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="uptimecheckresult",
            index=models.Index(
                fields=["website"], name="monitor_upt_website_79b9d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uptimecheckresult",
            index=models.Index(
                fields=["checked_at"], name="monitor_upt_checked_ed1175_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(fields=["user"], name="monitor_web_user_id_3a7772_idx"),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["is_active"], name="monitor_web_is_acti_957d31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["created_at"], name="monitor_web_created_990d1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["check_interval"], name="monitor_web_check_i_9d8ebb_idx"
            ),
        ),
    ]
