# Generated by Django 5.2.4 on 2025-09-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeat",
            name="next_due",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
