# Generated by Django 5.2.4 on 2025-09-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_remove_notificationpreference_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeat",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="For maintenance/pause window, If disabled, the website will not be checked.",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="For maintenance/pause window, If disabled, the website will not be checked.",
            ),
        ),
    ]
