# Generated by Django 5.2.4 on 2025-07-21 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0002_uptimecheckresult_monitor_upt_website_79b9d9_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="uptimecheckresult",
            name="monitor_upt_website_79b9d9_idx",
        ),
        migrations.RemoveIndex(
            model_name="uptimecheckresult",
            name="monitor_upt_checked_ed1175_idx",
        ),
        migrations.RemoveIndex(
            model_name="website",
            name="monitor_web_is_acti_957d31_idx",
        ),
        migrations.RemoveIndex(
            model_name="website",
            name="monitor_web_check_i_9d8ebb_idx",
        ),
        migrations.AddIndex(
            model_name="uptimecheckresult",
            index=models.Index(
                fields=["website", "checked_at"], name="monitor_upt_website_b9fb9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["is_active", "check_interval"],
                name="monitor_web_is_acti_296c42_idx",
            ),
        ),
    ]
