# Generated by Django 5.2.4 on 2025-07-21 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitor",
            "0003_remove_uptimecheckresult_monitor_upt_website_79b9d9_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="next_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["next_check_at"], name="monitor_web_next_ch_474ca8_idx"
            ),
        ),
    ]
