# Generated by Django 5.2.4 on 2025-10-24 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0003_heartbeat_is_active_alter_website_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(
                blank=True,
                help_text="Profile picture URL from OAuth provider",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="github_id",
            field=models.CharField(
                blank=True,
                help_text="GitHub OAuth user ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="Google OAuth user ID (sub claim from JWT)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
