# Generated by Django 5.2.4 on 2025-07-23 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0004_website_next_check_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="website",
            name="monitor_web_is_acti_296c42_idx",
        ),
        migrations.RemoveIndex(
            model_name="website",
            name="monitor_web_next_ch_474ca8_idx",
        ),
        migrations.AddIndex(
            model_name="website",
            index=models.Index(
                fields=["is_active", "next_check_at"],
                name="monitor_web_is_acti_89a791_idx",
            ),
        ),
    ]
