# Generated by Django 5.2.4 on 2025-11-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0004_customuser_avatar_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("slack", "Slack"),
                    ("whatsapp", "WhatsApp"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
