# Generated by Django 5.2.4 on 2025-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0005_remove_website_monitor_web_is_acti_296c42_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="is_down",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="website",
            name="last_downtime_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="last_recovered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
