# Generated by Django 5.2.4 on 2025-11-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0005_alter_notificationpreference_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeat",
            name="last_downtime_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="heartbeat",
            name="last_recovered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
