# Generated by Django 5.2.4 on 2025-07-23 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0006_website_is_down_website_last_downtime_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "website", "method")},
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["website", "alert_type", "is_active"],
                name="monitor_ale_website_a111b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["created_at"], name="monitor_ale_created_3af5b3_idx"
            ),
        ),
    ]
