# Generated by Django 5.2.4 on 2025-09-09 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0007_alter_notificationpreference_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uptimecheckresult",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="uptimecheckresult",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="expected_status",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="website",
            name="timeout_ms",
            field=models.IntegerField(
                default=5000,
                help_text="Maximum wait time (in milliseconds) for the request to respond, before you give up and mark it as failed.",
            ),
        ),
        migrations.CreateModel(
            name="HeartBeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "key",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        help_text="Expected interval in seconds (e.g. 86400 for daily)"
                    ),
                ),
                (
                    "grace_period",
                    models.IntegerField(
                        default=60, help_text="Extra time buffer in seconds"
                    ),
                ),
                (
                    "last_ping",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("up", "Up"),
                            ("down", "Down"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("fail", "Fail")],
                        max_length=20,
                    ),
                ),
                (
                    "runtime",
                    models.FloatField(
                        blank=True, help_text="Runtime in seconds", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "heartbeat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="monitor.heartbeat",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["heartbeat", "timestamp"],
                        name="monitor_pin_heartbe_0bbebd_idx",
                    ),
                    models.Index(
                        fields=["status"], name="monitor_pin_status_ffa182_idx"
                    ),
                ],
            },
        ),
    ]
